services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db

  product-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-product
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/product_db?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data: